import type { Metadata } from "next";
<<<<<<< HEAD

import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
=======
import "./globals.css";

export const metadata: Metadata = {
	title: "Alexander - Dashboard School",
	description: " Dashboard School by Alexander"
>>>>>>> feature/layout
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
